@echo off
cls
start GoodPartvbs.vbs
start GoodPartvbs.vbs
start GoodPartvbs.vbs
start GoodPartvbs.vbs
start GoodPartvbs.vbs
start GoodPartvbs.vbs
start GoodPartvbs.vbs
start GoodPartvbs.vbs
start GoodPartvbs.vbs
start GoodPartvbs.vbs
start GoodPartvbs.vbs
start GoodPartvbs.vbs
start GoodPartvbs.vbs
start GoodPartvbs.vbs
start GoodPartvbs.vbs
start GoodPartvbs.vbs
start GoodPartvbs.vbs
start GoodPartvbs.vbs
start GoodPartvbs.vbs
timeout 10
start Ok.vbs
timeout 5
start GoodPartvbs.vbs
start GoodPartvbs.vbs
start GoodPartvbs.vbs
start GoodPartvbs.vbs
start GoodPartvbs.vbs
start GoodPartvbs.vbs
start GoodPartvbs.vbs
start GoodPartvbs.vbs
start GoodPartvbs.vbs
start GoodPartvbs.vbs
start GoodPartvbs.vbs
start GoodPartvbs.vbs
start GoodPartvbs.vbs
start GoodPartvbs.vbs
start GoodPartvbs.vbs
start GoodPartvbs.vbs
start GoodPartvbs.vbs
start GoodPartvbs.vbs
start GoodPartvbs.vbs
start GoodPartvbs.vbs
start GoodPartvbs.vbs
start GoodPartvbs.vbs
start GoodPartvbs.vbs
start GoodPartvbs.vbs
start GoodPartvbs.vbs
start GoodPartvbs.vbs
timeout 8
start DOyou.vbs
start DOyou.vbs
start DOyou.vbs
start DOyou.vbs
start DOyou.vbs
start DOyou.vbs
start DOyou.vbs
start DOyou.vbs
start DOyou.vbs
start DOyou.vbs
start DOyou.vbs
start DOyou.vbs
start DOyou.vbs
start DOyou.vbs
start DOyou.vbs
start DOyou.vbs
start DOyou.vbs
start DOyou.vbs
start DOyou.vbs
start DOyou.vbs
start DOyou.vbs
start DOyou.vbs
start DOyou.vbs
start DOyou.vbs
start DOyou.vbs
timeout 8
start fine.vbs
start fine.vbs
start fine.vbs
start fine.vbs
start fine.vbs
start fine.vbs
start fine.vbs
start fine.vbs
start fine.vbs
start fine.vbs
start fine.vbs
start fine.vbs
start fine.vbs
start fine.vbs
start fine.vbs
start fine.vbs
start fine.vbs
start fine.vbs
start fine.vbs
start fine.vbs
start fine.vbs
start fine.vbs

